---
name: 'npm Lockfile Version'
description: 'Make sure the Lockfile version is correct in your project'
branding:
  icon: 'hash'
  color: 'green'
inputs:
  version:
    description: 'Optionally specify the lockfile version'
    default: 2
  path:
    description: 'Optionally specify path to lockfile'
    default: 'package-lock.json'
runs:
  using: 'composite'
  steps:
    - name: Check lockfile
      shell: bash
      run: ${{ github.action_path }}/script.sh "${{ inputs.version }}" "${{ inputs.path }}"
